### ISSUE TITLE
xproj files of tweaks freeze on downloading

### ISSUE THREAD

**Issue by isklikas** [SquaredTiki/Dringend-Issues#1]
Just wanted to let you know, that xproj files of tweaks freeze on downloading, even if they are very small files and projects. By killing the app, all I can do is make it appear on the menu, though it won't be fully downloaded. Here is a sample .xproj
https://www.dropbox.com/sh/5jkwwm4dx1hvz52/bhb_0BUPiU

**Comment by SquaredTiki** [comment]
Is this when you are importing a whole Xcode project from the main/home screen or when you are importing a single file to an already existing project?

**Comment by SquaredTiki** [comment]
In your Xcode project are there any items which don't exist (that would show up red in the Xcode file navigator)?

**Comment by isklikas** [comment]
This is when importing the whole Xcode project. No, all of them are available in the project navigator.

**Comment by isklikas** [comment]
This might be completely irrelevant, but as the frameworks used by tweaks are usually private frameworks, that are manually imported into the project folder, this might be causing a problem. Otherwise, I suspect it has trouble with importing files such as substrate.h, which are not located in the project folder, but in a folder that the compiler knows to look into.

**Comment by SquaredTiki** [comment]
I think you are right with the issue being with the private frameworks. The app looks for libsubstrate.dylib which is stored in /opt/iOSOpenDev/lib/libsubstrate.dylib however it does not have access to that directory to download it. I will implement a condition to prevent Dringend trying to download items which lye outside of Dropbox.

**Comment by isklikas** [comment]
Great, that should solve the bug. It is not that this is needed for the coding, the compiler only needs this file.

**Comment by SquaredTiki** [comment]
Resolved in Beta 3 which will be released soon.
