### ISSUE TITLE
Compiled app installation always fails

### ISSUE THREAD

**Issue by MaxDesiatov** [SquaredTiki/Dringend-Issues#101]
![image](https://cloud.githubusercontent.com/assets/112310/10559795/1810de52-74f0-11e5-96b1-82317f2a7ada.png)

The app was created from a "single view" app template wih no edits applied. After the app is compiled successfuly, it starts installing but always fails with an error as on screenshot.

iOS 9.0.2, iPad Mini 4, latest Dringend and The Constructor versions.

**Comment by SquaredTiki** [comment]
Are you running iOS 9? And can you confirm you are using the latest version? 

Josh (📱)

**Comment by MaxDesiatov** [comment]
Yes, iOS 9.0.2, Dringend 1.4.2

**Comment by SquaredTiki** [comment]
Thank you. Please could you plug your iPad into your Mac, open Xcode, navigate to devices and view the console for your iPad. If you could then try to run your project and copy the logs after the installation fails and paste them here that'd be very helpful to track down the issue.

Apologies for the inconvenience.

**Comment by MaxDesiatov** [comment]
```
Oct 17 19:56:14 Ifrit installd[47] <Notice>: 0x16e087000 -[MIClientConnection installPath:withOptions:completion:]: Install of "/var/mobile/Media/Downloads/9173420274645947878/-6968215552193474640" type Customer requested by itunesstored (pid 104)
Oct 17 19:56:15 Ifrit installd[47] <Notice>: 0x16e12f000 -[MIInstaller performInstallationWithError:]: Installing <MIInstallableBundle ID=com.maxdesiatov.DringendTest; Version=1, ShortVersion=1.0>
Oct 17 19:56:15 Ifrit misagent[135] <Notice>: attempt to install invalid profile: 0xe8008012
Oct 17 19:56:15 Ifrit installd[47] <Error>: 0x16e12f000 -[MIInstallableBundle _installEmbeddedProfileInBundle:]: Could not install embedded profile: 0xe8008012 (This provisioning profile cannot be installed on this device.)
Oct 17 19:56:15 Ifrit installd[47] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
Oct 17 19:56:15 Ifrit installd[47] <Error>: 0x16e12f000 +[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:]: 142: Failed to verify code signature of /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.PMZdoO/extracted/Payload/DringendTest.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)
Oct 17 19:56:15 Ifrit installd[47] <Error>: 0x16e12f000 -[MIInstaller performInstallationWithError:]: Verification stage failed
Oct 17 19:56:15 Ifrit itunesstored[104] <Error>: 0x16e247000 __MobileInstallationInstallForLaunchServices_block_invoke222: Returned error Error Domain=MIInstallerErrorDomain Code=13 "Failed to verify code signature of /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.PMZdoO/extracted/Payload/DringendTest.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)" UserInfo={LibMISErrorNumber=-402620395, LegacyErrorString=ApplicationVerificationFailed, SourceFileLine=142, FunctionName=+[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:], NSLocalizedDescription=Failed to verify code signature of /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.PMZdoO/extracted/Payload/DringendTest.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)}
Oct 17 19:56:15 Ifrit itunesstored[104] <Warning>: ERROR: MobileInstallationInstallForLaunchServices returned nil
Oct 17 19:56:15 Ifrit lsd[79] <Warning>: LaunchServices: Setting progress = FAILED for app com.maxdesiatov.DringendTest
Oct 17 19:56:15 Ifrit itunesstored[104] <Warning>: LaunchServices: installPhaseFinishedForProgress: com.maxdesiatov.DringendTest.Installing - <NSProgress: 0x1261a8960> : Parent: 0x0 / Fraction completed: 0.0000 / Completed: 0 of 100   called, removing progress from cache
Oct 17 19:56:15 Ifrit itunesstored[104] <Warning>: [ApplicationWorkspace]: Failed to install application: com.maxdesiatov.DringendTest; /var/mobile/Media/Downloads/9173420274645947878/-6968215552193474640; Error Domain=LaunchServicesError Code=0 "(null)" UserInfo={Error=ApplicationVerificationFailed, ErrorDetail=-402620395, ErrorDescription=Failed to verify code signature of /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.PMZdoO/extracted/Payload/DringendTest.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)}
Oct 17 19:56:15 Ifrit itunesstored[104] <Warning>: [ApplicationWorkspace] Install complete for download: 9173420274645947878 result: Failed
Oct 17 19:56:15 Ifrit itunesstored[104] <Warning>: [Download]: Fail download: 9173420274645947878 after error: Error Domain=SSMobileInstallationErrorDomain Code=0 "(null)" UserInfo={SSErrorInstallErrorNameKey=ApplicationVerificationFailed}
```

Seems like a provisioning profile error. Still would be nice if Dringend had a list of possible solution to errors like that displayed right on the screen after installation starts.

**Comment by SquaredTiki** [comment]
Indeed it does look like a provisioning profile error: `This provisioning profile cannot be installed on this device`. Not the most precise error but worth checking that the provisioning profile is a development one and that the device Dringend is running on is provisioned using it.

There's quite a wide variety of possible causes for such an error but I'll keep the suggestion of a possible help section with such details in mind.

**Comment by MaxDesiatov** [comment]
I hope this is possible for The Constructor to make those checks before starting the build.

**Comment by SquaredTiki** [comment]
What checks do you mean?

**Comment by MaxDesiatov** [comment]
"checking that the provisioning profile is a development one and that the device Dringend is running on is provisioned using it"

**Comment by SquaredTiki** [comment]
It is not possible to check which type of provisioning profile it is and whilst the profile itself contains a list of device UUIDs as it is not possible to retrieve this in Dringend it unfortunately can't be checked either. There is some reliance on the user knowing that the provisioning profile they choose must include their device in it, just like in Xcode.

**Comment by MaxDesiatov** [comment]
I know there is no way get UDID programatically, but what if there would be an input field in Dringend where I paste UDID as a user to make this automated check possible?

**Comment by SquaredTiki** [comment]
That is possible though some users make use of The Constructor with multiple devices which would complicate the matter.

**Comment by MaxDesiatov** [comment]
Thanks anyway, keep up the good work!

**Comment by SquaredTiki** [comment]
Thank you!
