### ISSUE TITLE
Builds but build and run fails with "Exporting project failed"

### ISSUE THREAD

**Issue by ezhes** [SquaredTiki/Dringend-Issues#103]
This doesn't seem to be the same as issue #93 because it fails even with the most basic single view (both objective-c and swift) app. I'm currently out and can't copy and paste the log, but I've got a screenshot here
![image](https://cloud.githubusercontent.com/assets/1606726/14651378/f3d3aa82-062c-11e6-9014-15e2673184ad.jpeg)

If I set it to keep projects I can successfully open and build them in Xcode. Thoughts?

**Comment by SquaredTiki** [comment]
This sounds like it may be a provisioning error that is causing Xcode to silently fail. Please could you try using [this beta version](http://dringend.cc/dl/constructor_1.1.1.zip) of The Constructor and check the logs again for a new one that indicates the output of `stderr`.

**Comment by ezhes** [comment]
So the beta version works just fine with the exact same provisioning profile. Not sure what's changed in this version, but something's working. 

`iPhone Developer: * (2017-8-17)` is the profile name

**Comment by SquaredTiki** [comment]
Glad to hear it. It may be related to some changes made to do with symbolic links and CocoaPods. I'll be releasing it as a full update soon.
