### ISSUE TITLE
It is not working for me

### ISSUE THREAD

**Issue by ShawnBaek** [SquaredTiki/Dringend-Issues#108]
I had trying to start build.

Zipping project ...

Compiling project ...

and...Got an message 

**"Initiating build failed"

An error occurred whilst attempting to initiate the build process with the build server, the error is as follow: Read operation timed out**

I had import from dropbox and I had checked my code signing and also double checked my mac's ip.

I had trying to build iPad and iPhone...both are not working..

My mac is 2015 late version...macbook pro 15"

and My iPad and iPhone is ios9.

My project using the cocoa pods..

**Comment by SquaredTiki** [comment]
Please continue our conversation via email.
