### ISSUE TITLE
Not compiling for swift 3.0

### ISSUE THREAD

**Issue by joseortizcostadev** [SquaredTiki/Dringend-Issues#109]
Hi, 

First of all, I like this development tool a lot. Thanks for bringing the Xcode development to my iPad. 

Are you going to implement support for compiling in swift 3.0 anytime soon? I am developing in Xcode 8 beta 5 and Swift 3.0 for IOS 10, and I am getting some errors in your app related to changes in the code architecture from Swift 2.2 to Swift 3.0.

Thanks.

**Comment by SquaredTiki** [comment]
Hi Jose,

Sorry for not getting back to you sooner, GitHub notification didn't come through or got lost. It should be possible to compile imported Swift 3 projects without issue, what errors are you seeing?

Thanks,
Josh

**Comment by joseortizcostadev** [comment]
Hi Josh, 

The errors I am seeing are typical of the migration from Swift 2.2 to 3.0 such as the underscore in methods header and many more..... It is clear that those errors occur because compiler is not compiling Swift 3.0 code. I can compile the same code in my mac with Xcode 8 with Swift 3.0, and there are no exceptions/errors. 

Thank you,
Jose.

**Comment by SquaredTiki** [comment]
The Constructor uses `xcodebuild` so the first thing to check would be that the command line tools are set to use Xcode 8. Please could you go into Xcode's preferences and then 'Locations' and make sure the 'Command Line Tools' dropdown has 'Xcode 8.0 (…)' selected.

**Comment by joseortizcostadev** [comment]
Yes, you were right I had it set to Xcode 7. However, it is not compiling yet. But this time I cannot see the error because the box informing about the errors is not popping up.

Thanks.

**Comment by SquaredTiki** [comment]
Glad to hear that was it 😄 As in Dringend isn't showing any errors at all? If so, please could you open Console.app on your Mac, select `system.log` and share the logs that The Constructor makes during compilation?

**Comment by joseortizcostadev** [comment]
These are the logs: 
Sep 27 10:41:43 Joses-MacBook-Pro The Constructor[3573]: <Builder> Port mapping did come to conclussion
Sep 27 10:41:43 Joses-MacBook-Pro The Constructor[3573]: <Builder> ... And the port mapping was successful
Sep 27 10:41:43 Joses-MacBook-Pro The Constructor[3573]: <Constructor> Port forwarding status updated to: Successful
Sep 27 10:41:50 Joses-MacBook-Pro logd[78]: Time changed, updating file headers

In this launch, it popped up the message error which says: 

"An error occurred while attempting to initiate the build process with the built server, the error is as follows: Operation timed out"

**Comment by SquaredTiki** [comment]
This now sounds to be an unrelated issue regarding port forwarding. Is the IP you have for the host in Dringend still the IP of the Mac running the The Constructor?

**Comment by joseortizcostadev** [comment]
Let me create another host to see if that is the problem.

**Comment by joseortizcostadev** [comment]
Nope, the port is not the problem. I have to run out. I'll try to solve this tomorrow again. 

Thanks a lot for your help.

**Comment by SquaredTiki** [comment]
No worries, let me know how it goes!

**Comment by robertiii** [comment]
Says port mapping was unsuccessful.

Sep 27 00:01:54 Roberts-MacBook-Pro-2 The Constructor[25782]: <Builder> Beginning process of port mapping
Sep 27 00:01:54 Roberts-MacBook-Pro-2 The Constructor[25782]: <Constructor> Port forwarding status updated to: In progress
Sep 27 00:01:54 Roberts-MacBook-Pro-2 The Constructor[25782]: -[TCMNATPMPPortMapper stopListeningToExternalIPAddressChanges], socket:0x0
Sep 27 00:01:54 Roberts-MacBook-Pro-2 The Constructor[25782]: <Builder> Port mapping did find router
Sep 27 00:01:54 Roberts-MacBook-Pro-2 The Constructor[25782]: <Builder> ... However this was a red herring and the router does not in fact exist
Sep 27 00:01:54 Roberts-MacBook-Pro-2 The Constructor[25782]: <Constructor> Port forwarding status updated to: No Router found
Sep 27 00:01:55 Roberts-MacBook-Pro-2 The Constructor[25782]: -[TCMPortMapper decreaseWorkCount:] 1 (null)
