### ISSUE TITLE
Will not get past this point....

### ISSUE THREAD

**Issue by robertiii** [SquaredTiki/Dringend-Issues#115]
Jan 23 14:14:20 --- last message repeated 1 time ---
Jan 23 14:14:20 Roberts-MacBook-Pro-2 The Constructor[17516]: <Builder> did accept new connection from socket
Jan 23 14:14:20 Roberts-MacBook-Pro-2 The Constructor[17516]: <Builder> did read header from socket
Jan 23 14:14:20 Roberts-MacBook-Pro-2 The Constructor[17516]: <Builder> Socket defined header dictionary as {
	    buildOptions =     {
	        destination = "generic/platform=iOS";
	        scheme = "Freezer Log";
	    };
	    buildType = 1;
	    dataLength = 56626409;
	    exportOptions =     {
	        exportFormat = IPA;
	    };
	}
Jan 23 14:14:20 Roberts-MacBook-Pro-2 The Constructor[17516]: <Builder> Writing to socket that transmission was received
Jan 23 14:14:20 Roberts-MacBook-Pro-2 The Constructor[17516]: <Builder> did send data with tag 32
Jan 23 14:14:20 Roberts-MacBook-Pro-2 The Constructor[17516]: <Builder> did send data with tag 0
Jan 23 14:14:30 Roberts-MacBook-Pro-2 com.apple.xpc.launchd[1] (com.apple.nowplayingtouchui): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.

**Comment by SquaredTiki** [comment]
Sorry for the delay in getting back to you, for some reasons GitHub has not been sending me notifications. 

Please could you give a beta version of The Constructor a try? You can find it here: http://dringend.cc/dl/constructor_1.1.1.zip.

If your project is set to use automatic code signing then leave the Code Signing Identity field blank and set provisioning profile to ‘Use project default’. If it's set to manual code signing then please configure the Code Signing Identity and Provisioning Profile appropriately. 

I'll be releasing this as an update and updating the FAQ soon.

**Comment by robertiii** [comment]
The beta says that it is corrupt and cannot open the zip. I unzipped on my ipad and the mac says that it cannot run.

**Comment by SquaredTiki** [comment]
Please could you screenshot the message you are seeing and try re-downloading?

**Comment by robertiii** [comment]
It worked! Not sure what went wrong. Is there a way to set up port forwarding without Constructor automatically setting up. The router does not allow automatic but allows me to open up ports manually.

**Comment by SquaredTiki** [comment]
Perfect! You can set it up manually on your router, just open up the port you've selected in The Constructor and forward the port from the public interface through to the LAN IP address of the Mac running The Constructor.
