### ISSUE TITLE
Doesn't compile with latest Xcode

### ISSUE THREAD

**Issue by JoelConnett** [SquaredTiki/Dringend-Issues#116]
As far as I can tell this app either doesn't work with Xcode 8.2.1 or swift 3. I haven't tried an objective c project yet. 

Steps to reproduce:
1. Create a new project (either in the app or Xcode).
2. try to build the app
3. The error "Archiving the project failed" appears

Note that when I create the app with Xcode building works fine. When I create it with the app it complains a signing identity hasn't been created.

**Comment by SquaredTiki** [comment]
Sorry for the delay in getting back to you, for some reasons GitHub has not been sending me notifications. 

Please could you give a beta version of The Constructor a try? You can find it here: http://dringend.cc/dl/constructor_1.1.1.zip.

If your project is set to use automatic code signing then leave the Code Signing Identity field blank and set provisioning profile to ‘Use project default’. If it's set to manual code signing then please configure the Code Signing Identity and Provisioning Profile appropriately. 

I'll be releasing this as an update and updating the FAQ soon.
