### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by laynet79** [SquaredTiki/Dringend-Issues#117]
Just purchased Dringend on my iPhone, installed The Constructor app on my iMac.  Initially got connection errors when attempting to build.  Got a dedicated IP address from my ISP.  Now when I try to build I get an an immediate Failed message.  Don't know what to look at next. I have also setup a dropbox account and have installed the dropbox app on my phone and configured it to my dropbox account.

I believe that I have my IP address/port correct now, and my apple developer key entered correctly

I am running Xcode 8.3

Any Help would be appreciated.

**Comment by SquaredTiki** [comment]
Sorry for the delay in getting back to you, for some reasons GitHub has not been sending me notifications. 

Please could you give a beta version of The Constructor a try? You can find it here: http://dringend.cc/dl/constructor_1.1.1.zip.

If your project is set to use automatic code signing then leave the Code Signing Identity field blank and set provisioning profile to ‘Use project default’. If it's set to manual code signing then please configure the Code Signing Identity and Provisioning Profile appropriately. 

I'll be releasing this as an update and updating the FAQ soon.

**Comment by laynet79** [comment]
I tried the beta as you suggested with the same results (quickly reports
failure).

A little more background about my test case.  I created a new project on my
iPhone using the single view application (swift, iPhone), gave it a name
and company ID.  Didn't see anywhere to set manual/auto code signing.  Then
hit the build button (quick fail message).

On my iMac I had Constructor running (tried blank code signing field with
use project default, and also tried iPhone dev key with IOS team
provisioning profile.

When I first purchased this product I was getting a connection failure.  I
then got a dedicated IP address from my ISP and that went away.  Also tried
my local network IP with same quick failure message)

Please let me know if you have any other suggestions.
Thanks,
Layne

**Comment by SquaredTiki** [comment]
There is an issue with the sample projects created by Dringend at the moment which may be causing them to fail to run on device (I'll be fixing this is the next update). In the meantime would you be able to create a project in Xcode (or use an existing one) and import it into Dringend?

This will have the code signing set up likely as automatic by default so you can configure The Constructor as mentioned above for that and it should work correctly.

If not, then please could you grab the logs from Console.app on your Mac which are output by The Constructor during the build process?

Thanks very much for your patience and help sorting this out!

**Comment by laynet79** [comment]
Thanks for your help,  I can now compile and it says that it was successful
(using the hammer button).  But if I select the run triangle button I get
the "Exporting the project failed" message.

I created my project on the Mac (Xcode 8.3, single view app, default
settings), uploaded it to dropbox, imported it on my phone and built.
Constructor has the code signing field blank, and the provisioning profile
set to "use project defaults"

I'm I missing some setup step?

Thanks again.

**Comment by SquaredTiki** [comment]
I'm glad to hear that building is now working successfully. To track down the building and run issue please could you grab the logs from Console.app on your Mac which are output by The Constructor during the build process?

Thanks,
Josh

**Comment by laynet79** [comment]
I hope this is the log you're talking about "system.log" from the
console.app.

it shows the launching of the Constructor app, then pressing the hammer
build button, and then pressing the run triangle button.

Thanks

**Comment by SquaredTiki** [comment]
I can't see any logs in that email/reply unfortunately.

Please open `Console.app`, leave your device selected on the left (if on Sierra) then search for `The Constructor`. After running from Dringend (the triangle), select all of the logs, copy them and please paste them into a comment here.

![screen shot 2017-04-07 at 21 33 13](https://cloud.githubusercontent.com/assets/146159/24818841/01774522-1bda-11e7-856b-517fd870d3c9.png)

**Comment by laynet79** [comment]
Sorry about that.  Here's what it captured

default 17:03:21.761359 -0600 The Constructor <Builder> did accept new
connection from socket

default 17:03:21.767858 -0600 The Constructor <Builder> did read header
from socket

default 17:03:21.768089 -0600 The Constructor <Builder> Socket defined
header dictionary as {

    buildOptions =     {

        destination = "generic/platform=iOS";

        scheme = DrawFun;

    };

    buildType = 1;

    dataLength = 22575;

    exportOptions =     {

        exportFormat = IPA;

    };

}

default 17:03:21.768155 -0600 The Constructor <Builder> Writing to socket
that transmission was received

default 17:03:21.768286 -0600 The Constructor <Builder> did send data with
tag 32

default 17:03:21.768358 -0600 The Constructor <Builder> did send data with
tag 0

default 17:03:21.787626 -0600 The Constructor <Builder> did read project
data from socket

default 17:03:21.787777 -0600 The Constructor Number of operations: 1,
operations array count: 1, maximum concurrent: 4

default 17:03:21.787785 -0600 The Constructor ***-----|Dispatch
operation|-----***

default 17:03:21.788806 -0600 The Constructor <Builder> Project zip file
successfully saved to: /Users/layne/Library/Application Support/The
Constructor/82873E61-21CF-4A4B-866F-12DBDB67E0C3/ZippedProject.zip

default 17:03:21.800713 -0600 The Constructor <Builder> Archiving and
exporting project located in directory: /Users/layne/Library/Application
Support/The Constructor/82873E61-21CF-4A4B-866F-12DBDB67E0C3

default 17:03:21.800797 -0600 The Constructor <Builder> Archive & export:
Beginning archive

default 17:03:21.800928 -0600 The Constructor <Builder> Building project

default 17:03:35.068079 -0600 The Constructor <Builder> Archive & export:
Archive complete, success? Yes!

default 17:03:35.068376 -0600 The Constructor <Builder> Archive output:
User defaults from command line:

    IDEArchivePathOverride = /Users/layne/Library/Application Support/The
Constructor/82873E61-21CF-4A4B-866F-12DBDB67E0C3/Archive.xcarchive


=== BUILD TARGET DrawFun OF PROJECT DrawFun WITH CONFIGURATION Release ===


Check dependencies


Write auxiliary files

write-file
/Users/layne/Library/Developer/Xcode/DerivedData/DrawFun-hhdjajwzffcxgcdgxvffgpzaxwwv/Build/Intermediates/ArchiveIntermediates/DrawFun/IntermediateBuildFilesPath/DrawFun.build/Release-iphoneos/DrawFun.build/DrawFun.hmap

/bin/mkdir -p
/Users/layne/Library/Developer/Xcode/DerivedData/DrawFun-hhdjajwzffcxgcdgxvffgpzaxwwv/Build/Intermediates/ArchiveIntermediates/DrawFun/IntermediateBuildFilesPath/DrawFun.build/Release-iphoneos/DrawFun.build/Objects-normal/armv7

write-file
/Users/layne/Library/Developer/Xcode/DerivedData/DrawFun-hhdjajwzffcxgcdgxvffgpzaxwwv/Build/Intermediates/ArchiveIntermediates/DrawFun/IntermediateBuildFilesPath/DrawFun.build/Release-iphoneos/DrawFun.build/Objects-norma

default 17:03:35.068705 -0600 The Constructor <Builder> Archive & export:
Beginning export

default 17:03:35.069049 -0600 The Constructor <Builder> Building project

default 17:03:35.327697 -0600 The Constructor <Builder> Data was output to
stderr during current build process, output was as follows:

xcodebuild: error: invalid option '-exportFormat'


Usage: xcodebuild [-project <projectname>] [[-target
<targetname>]...|-alltargets] [-configuration <configurationname>] [-arch
<architecture>]... [-sdk [<sdkname>|<sdkpath>]] [-showBuildSettings]
[<buildsetting>=<value>]... [<buildaction>]...

       xcodebuild [-project <projectname>] -scheme <schemeName>
[-destination <destinationspecifier>]... [-configuration
<configurationname>] [-arch <architecture>]... [-sdk [<sdkname>|<sdkpath>]]
[-showBuildSettings] [<buildsetting>=<value>]... [<buildaction>]...

       xcodebuild -workspace <workspacename> -scheme <schemeName>
[-destination <destinationspecifier>]... [-configuration
<configurationname>] [-arch <architecture>]... [-sdk [<sdkname>|<sdkpath>]]
[-showBuildSettings] [<buildsetting>=<value>]... [<buildaction>]...

       xcodebuild -version [-sdk [<sdkfullpath>|<sdkname>] [<infoitem>] ]

       xcodebuild -list [[-project

default 17:03:35.328018 -0600 The Constructor <Builder> Archive & export:
Export complete, success? Nope

default 17:03:35.328071 -0600 The Constructor <Builder> Export output:

default 17:03:35.328335 -0600 The Constructor <Builder> Archive and export
complete, exported to: (null)

default 17:03:35.328389 -0600 The Constructor Return--> Number of
operations: 0, operations array count: 0, maximum concurrent: 4

default 17:03:35.329182 -0600 The Constructor <Builder> Deleting project
working directory (/Users/layne/Library/Application Support/The
Constructor/82873E61-21CF-4A4B-866F-12DBDB67E0C3) on build completion

default 17:03:35.329351 -0600 The Constructor <Builder> did send data with
tag 433

default 17:03:35.329418 -0600 The Constructor <Builder> did send data with
tag 0

default 17:03:35.489486 -0600 The Constructor <Builder> did disconnect from
socket

**Comment by SquaredTiki** [comment]
Perfect, thank you very much. It looks like this issue relates to Xcode 8.3. Please could you try this custom build of The Constructor for me and let me know if it works (and if not, share the logs again)?

[The Constructor (1.1.1-L1)](https://github.com/SquaredTiki/Dringend-Issues/files/907473/The.Constructor.zip)

Thank you so much for your patience and help getting to the bottom of this!

**Comment by laynet79** [comment]
Same error message "Exporting the project failed".  Note that I upgraded to
Xcode 8.3.1 yesterday.  Hope that didn't mess up the test.

default 08:17:22.847260 -0600 The Constructor <Builder> did accept new
connection from socket
default 08:17:22.848423 -0600 The Constructor <Builder> did read header
from socket
default 08:17:22.848587 -0600 The Constructor <Builder> Socket defined
header dictionary as {
    buildOptions =     {
        destination = "generic/platform=iOS";
        scheme = DrawFun;
    };
    buildType = 1;
    dataLength = 22573;
    exportOptions =     {
        exportFormat = IPA;
    };
}
default 08:17:22.848652 -0600 The Constructor <Builder> Writing to socket
that transmission was received
default 08:17:22.848778 -0600 The Constructor <Builder> did send data with
tag 32
default 08:17:22.848837 -0600 The Constructor <Builder> did send data with
tag 0
default 08:17:22.869289 -0600 The Constructor <Builder> did read project
data from socket
default 08:17:22.869479 -0600 The Constructor Number of operations: 1,
operations array count: 1, maximum concurrent: 4
default 08:17:22.869488 -0600 The Constructor ***-----|Dispatch
operation|-----***
default 08:17:22.874034 -0600 The Constructor <Builder> Project zip file
successfully saved to: /Users/layne/Library/Application Support/The
Constructor/FEEEE809-87AB-4899-8E19-873AED11FA4C/ZippedProject.zip
default 08:17:22.884807 -0600 The Constructor <Builder> Archiving and
exporting project located in directory: /Users/layne/Library/Application
Support/The Constructor/FEEEE809-87AB-4899-8E19-873AED11FA4C
default 08:17:22.884885 -0600 The Constructor <Builder> Archive & export:
Beginning archive
default 08:17:22.885013 -0600 The Constructor <Builder> Building project
default 08:17:28.879289 -0600 The Constructor <Builder> Archive & export:
Archive complete, success? Yes!
default 08:17:28.879413 -0600 The Constructor <Builder> Archive output:
User defaults from command line:
    IDEArchivePathOverride = /Users/layne/Library/Application Support/The
Constructor/FEEEE809-87AB-4899-8E19-873AED11FA4C/Archive.xcarchive

=== BUILD TARGET DrawFun OF PROJECT DrawFun WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file
/Users/layne/Library/Developer/Xcode/DerivedData/DrawFun-dvzzaoubbhrvlafvfdupctrrpyqj/Build/Intermediates/ArchiveIntermediates/DrawFun/IntermediateBuildFilesPath/DrawFun.build/Release-iphoneos/DrawFun.build/DrawFun.hmap
/bin/mkdir -p
/Users/layne/Library/Developer/Xcode/DerivedData/DrawFun-dvzzaoubbhrvlafvfdupctrrpyqj/Build/Intermediates/ArchiveIntermediates/DrawFun/IntermediateBuildFilesPath/DrawFun.build/Release-iphoneos/DrawFun.build/Objects-normal/armv7
write-file
/Users/layne/Library/Developer/Xcode/DerivedData/DrawFun-dvzzaoubbhrvlafvfdupctrrpyqj/Build/Intermediates/ArchiveIntermediates/DrawFun/IntermediateBuildFilesPath/DrawFun.build/Release-iphoneos/DrawFun.build/Objec<…>
default 08:17:28.879592 -0600 The Constructor <Builder> Archive & export:
Beginning export
default 08:17:28.879918 -0600 The Constructor <Builder> Building project
default 08:17:28.945125 -0600 The Constructor <Builder> Data was output to
stderr during current build process, output was as follows:
xcodebuild: error: invalid option '-exportWithOriginalSigningIdentity'

Usage: xcodebuild [-project <projectname>] [[-target
<targetname>]...|-alltargets] [-configuration <configurationname>] [-arch
<architecture>]... [-sdk [<sdkname>|<sdkpath>]] [-showBuildSettings]
[<buildsetting>=<value>]... [<buildaction>]...
       xcodebuild [-project <projectname>] -scheme <schemeName>
[-destination <destinationspecifier>]... [-configuration
<configurationname>] [-arch <architecture>]... [-sdk [<sdkname>|<sdkpath>]]
[-showBuildSettings] [<buildsetting>=<value>]... [<buildaction>]...
       xcodebuild -workspace <workspacename> -scheme <schemeName>
[-destination <destinationspecifier>]... [-configuration
<configurationname>] [-arch <architecture>]... [-sdk [<sdkname>|<sdkpath>]]
[-showBuildSettings] [<buildsetting>=<value>]... [<buildaction>]...
       xcodebuild -version [-sdk [<sdkfullpath>|<sdkname>] [<infoitem>] ]
     <…>
default 08:17:28.945406 -0600 The Constructor <Builder> Archive & export:
Export complete, success? Nope
default 08:17:28.945463 -0600 The Constructor <Builder> Export output:
default 08:17:28.945578 -0600 The Constructor <Builder> Archive and export
complete, exported to: (null)
default 08:17:28.945634 -0600 The Constructor Return--> Number of
operations: 0, operations array count: 0, maximum concurrent: 4
default 08:17:28.946406 -0600 The Constructor <Builder> Deleting project
working directory (/Users/layne/Library/Application Support/The
Constructor/FEEEE809-87AB-4899-8E19-873AED11FA4C) on build completion
default 08:17:28.946584 -0600 The Constructor <Builder> did send data with
tag 433
default 08:17:28.946674 -0600 The Constructor <Builder> did send data with
tag 0
default 08:17:29.106233 -0600 The Constructor <Builder> did disconnect from
socket

**Comment by SquaredTiki** [comment]
Sorry about that, looks like I missed one change that was needed. Thank you again for the logs though. Here's a new build for you to test with:

[The Constructor (1.1.1-L2)](https://github.com/SquaredTiki/Dringend-Issues/files/907505/The.Constructor.app.zip)

**Comment by laynet79** [comment]
No problem.  Thanks for working on a fix. Still fails with the following
log.

default 08:32:53.259253 -0600 The Constructor <Builder> did accept new
connection from socket
default 08:32:53.261921 -0600 The Constructor <Builder> did read header
from socket
default 08:32:53.262122 -0600 The Constructor <Builder> Socket defined
header dictionary as {
    buildOptions =     {
        destination = "generic/platform=iOS";
        scheme = DrawFun;
    };
    buildType = 1;
    dataLength = 22575;
    exportOptions =     {
        exportFormat = IPA;
    };
}
default 08:32:53.262253 -0600 The Constructor <Builder> Writing to socket
that transmission was received
default 08:32:53.262381 -0600 The Constructor <Builder> did send data with
tag 32
default 08:32:53.262443 -0600 The Constructor <Builder> did send data with
tag 0
default 08:32:53.277946 -0600 The Constructor <Builder> did read project
data from socket
default 08:32:53.278160 -0600 The Constructor Number of operations: 1,
operations array count: 1, maximum concurrent: 4
default 08:32:53.278193 -0600 The Constructor ***-----|Dispatch
operation|-----***
default 08:32:53.282641 -0600 The Constructor <Builder> Project zip file
successfully saved to: /Users/layne/Library/Application Support/The
Constructor/63410329-8C41-4C18-BCAF-073CC8E598C8/ZippedProject.zip
default 08:32:53.296427 -0600 The Constructor <Builder> Archiving and
exporting project located in directory: /Users/layne/Library/Application
Support/The Constructor/63410329-8C41-4C18-BCAF-073CC8E598C8
default 08:32:53.296786 -0600 The Constructor <Builder> Archive & export:
Beginning archive
default 08:32:53.296938 -0600 The Constructor <Builder> Building project
default 08:32:59.313094 -0600 The Constructor <Builder> Archive & export:
Archive complete, success? Yes!
default 08:32:59.313345 -0600 The Constructor <Builder> Archive output:
User defaults from command line:
    IDEArchivePathOverride = /Users/layne/Library/Application Support/The
Constructor/63410329-8C41-4C18-BCAF-073CC8E598C8/Archive.xcarchive

=== BUILD TARGET DrawFun OF PROJECT DrawFun WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file
/Users/layne/Library/Developer/Xcode/DerivedData/DrawFun-fwdsyowpgkacfrddmdcdyzjkaibm/Build/Intermediates/ArchiveIntermediates/DrawFun/IntermediateBuildFilesPath/DrawFun.build/Release-iphoneos/DrawFun.build/DrawFun.hmap
/bin/mkdir -p
/Users/layne/Library/Developer/Xcode/DerivedData/DrawFun-fwdsyowpgkacfrddmdcdyzjkaibm/Build/Intermediates/ArchiveIntermediates/DrawFun/IntermediateBuildFilesPath/DrawFun.build/Release-iphoneos/DrawFun.build/Objects-normal/armv7
write-file
/Users/layne/Library/Developer/Xcode/DerivedData/DrawFun-fwdsyowpgkacfrddmdcdyzjkaibm/Build/Intermediates/ArchiveIntermediates/DrawFun/IntermediateBuildFilesPath/DrawFun.build/Release-iphoneos/DrawFun.build/Objec<…>
default 08:32:59.313807 -0600 The Constructor <Builder> Archive & export:
Beginning export
default 08:32:59.314305 -0600 The Constructor <Builder> Building project
default 08:32:59.378980 -0600 The Constructor <Builder> Data was output to
stderr during current build process, output was as follows:
xcodebuild: error: The flag -exportOptionsPlist is required when specifying
-exportArchive.
default 08:32:59.379241 -0600 The Constructor <Builder> Archive & export:
Export complete, success? Nope
default 08:32:59.379330 -0600 The Constructor <Builder> Export output:
default 08:32:59.379454 -0600 The Constructor <Builder> Archive and export
complete, exported to: (null)
default 08:32:59.379511 -0600 The Constructor Return--> Number of
operations: 0, operations array count: 0, maximum concurrent: 4
default 08:32:59.380253 -0600 The Constructor <Builder> Deleting project
working directory (/Users/layne/Library/Application Support/The
Constructor/63410329-8C41-4C18-BCAF-073CC8E598C8) on build completion
default 08:32:59.380367 -0600 The Constructor <Builder> did send data with
tag 433
default 08:32:59.380428 -0600 The Constructor <Builder> did send data with
tag 0
default 08:32:59.521992 -0600 The Constructor <Builder> did disconnect from
socket

**Comment by SquaredTiki** [comment]
Thanks for that, I've been able to re-create the issue now and it seems that 8.3 has changed `xcodebuild`'s export process more than I originally expected. I'm working on changes to fix the issue now.

**Comment by laynet79** [comment]
Thanks,  let me know how it goes.

Layne

**Comment by SquaredTiki** [comment]
Hey Layne,

Here's a new build that I've tested works with Xcode 8.3.1 myself, it should handle the various changes that 8.3 made to `xcodebuild`.  

[The Constructor (1.1.1-L3)](https://github.com/SquaredTiki/Dringend-Issues/files/907556/The.Constructor.app.zip)

**Comment by laynet79** [comment]
Works like a champ. Thanks so much.  When do you think you will release
this fix? Do you have plans to fix the on-device project templates?  This
is an exciting product.  Now I need to figure out how to update the
negative review I posted.

Thanks again,
Layne

**Comment by SquaredTiki** [comment]
Perfect, I'm very glad to hear it's working now! I plan to release this update to The Constructor this coming week. An update to Dringend with fixes for project templates and some other minor issues will likely come later this month. 

Thanks very much for your help and I'd really appreciate if you could update your review, going to the Dringend on the App Store then following through as if you were to write a new review should allow you to edit yours.  

Best,
Josh
