### ISSUE TITLE
Archiving the project failed

### ISSUE THREAD

**Issue by faridk** [SquaredTiki/Dringend-Issues#121]
I can only build an app but not run it. I get the "Archiving the project failed" message.

error	12:03:55.882790 -0800	The Constructor	        AEGetDescData of non-desc type 'reco' not a good idea
default	12:03:55.933335 -0800	The Constructor	UNIX error exception: 17
default	12:03:55.940487 -0800	The Constructor	UNIX error exception: 17
default	12:03:55.949120 -0800	The Constructor	<Constructor> Initially setting provisioning profile to: 2ddfb1a9-9588-490c-b592-12532a064c0e (iOS Team Provisioning Profile: faridk.imagenhance)
default	12:03:58.093385 -0800	The Constructor	<Builder> Port mapping did find router
default	12:03:58.955780 -0800	The Constructor	<Builder> Port mapping did come to conclussion
default	12:03:58.955865 -0800	The Constructor	<Builder> ... And the port mapping was successful
default	12:03:58.955932 -0800	The Constructor	<Constructor> Port forwarding status updated to: Successful
default	12:04:05.644923 -0800	The Constructor	LSExceptions shared instance invalidated for timeout.
default	12:05:14.595436 -0800	The Constructor	<Builder> did accept new connection from socket
default	12:05:14.596182 -0800	The Constructor	<Builder> did read header from socket
default	12:05:14.596733 -0800	The Constructor	<Builder> Socket defined header dictionary as {
    buildOptions =     {
        destination = "generic/platform=iOS";
        scheme = imagenhance;
    };
    buildType = 0;
    dataLength = 18103;
    exportOptions =     {
    };
}
default	12:05:14.596875 -0800	The Constructor	<Builder> Writing to socket that transmission was received
default	12:05:14.597861 -0800	The Constructor	<Builder> did send data with tag 32
default	12:05:14.598044 -0800	The Constructor	<Builder> did send data with tag 0
default	12:05:14.619251 -0800	The Constructor	<Builder> did read project data from socket
default	12:05:14.619637 -0800	The Constructor	***-----|Dispatch operation|-----***
default	12:05:14.619638 -0800	The Constructor	Number of operations: 1, operations array count: 1, maximum concurrent: 4
default	12:05:14.624133 -0800	The Constructor	<Builder> Project zip file successfully saved to: /Users/faridk/Library/Application Support/The Constructor/0D01F11B-D51F-41B9-B1B8-1775758619CE/ZippedProject.zip
default	12:05:14.669679 -0800	The Constructor	<Builder> Building project located in directory: /Users/faridk/Library/Application Support/The Constructor/0D01F11B-D51F-41B9-B1B8-1775758619CE
default	12:05:14.670106 -0800	The Constructor	<Builder> Building project
default	12:05:14.678225 -0800	The Constructor	<Builder> Data was output to stderr during current build process, output was as follows:
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
default	12:05:14.678395 -0800	The Constructor	<Builder> Build: Build complete, success? Nope
default	12:05:14.678497 -0800	The Constructor	<Builder> Build: Build output:
default	12:05:14.678579 -0800	The Constructor	Return--> Number of operations: 0, operations array count: 0, maximum concurrent: 4
default	12:05:14.678759 -0800	The Constructor	<Builder> Deleting project working directory (/Users/faridk/Library/Application Support/The Constructor/0D01F11B-D51F-41B9-B1B8-1775758619CE) on build completion
default	12:05:14.679095 -0800	The Constructor	<Builder> did send data with tag 433
default	12:05:14.679276 -0800	The Constructor	<Builder> did send data with tag 0
default	12:05:14.715894 -0800	The Constructor	<Builder> did disconnect from socket
default	12:05:18.075156 -0800	The Constructor	<Builder> did accept new connection from socket
default	12:05:18.097042 -0800	The Constructor	<Builder> did read header from socket
default	12:05:18.097524 -0800	The Constructor	<Builder> Socket defined header dictionary as {
    buildOptions =     {
        destination = "generic/platform=iOS";
        scheme = imagenhance;
    };
    buildType = 1;
    dataLength = 18103;
    exportOptions =     {
        exportFormat = IPA;
    };
}
default	12:05:18.097786 -0800	The Constructor	<Builder> Writing to socket that transmission was received
default	12:05:18.098101 -0800	The Constructor	<Builder> did send data with tag 32
default	12:05:18.098309 -0800	The Constructor	<Builder> did send data with tag 0
default	12:05:18.130867 -0800	The Constructor	<Builder> did read project data from socket
default	12:05:18.131278 -0800	The Constructor	Number of operations: 1, operations array count: 1, maximum concurrent: 4
default	12:05:18.131561 -0800	The Constructor	***-----|Dispatch operation|-----***
default	12:05:18.133056 -0800	The Constructor	<Builder> Project zip file successfully saved to: /Users/faridk/Library/Application Support/The Constructor/D871635C-C89D-470D-81F4-67E202887FBA/ZippedProject.zip
default	12:05:18.176700 -0800	The Constructor	<Builder> Archiving and exporting project located in directory: /Users/faridk/Library/Application Support/The Constructor/D871635C-C89D-470D-81F4-67E202887FBA
default	12:05:18.177231 -0800	The Constructor	<Builder> Archive & export: Beginning archive
default	12:05:18.177687 -0800	The Constructor	<Builder> Building project
default	12:05:18.182724 -0800	The Constructor	<Builder> Data was output to stderr during current build process, output was as follows:
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
default	12:05:18.184441 -0800	The Constructor	<Builder> Archive & export: Archive complete, success? Nope
default	12:05:18.184527 -0800	The Constructor	<Builder> Archive output:
default	12:05:18.184736 -0800	The Constructor	<Builder> Archive and export complete, exported to: (null)
default	12:05:18.184938 -0800	The Constructor	Return--> Number of operations: 0, operations array count: 0, maximum concurrent: 4
default	12:05:18.185528 -0800	The Constructor	<Builder> Deleting project working directory (/Users/faridk/Library/Application Support/The Constructor/D871635C-C89D-470D-81F4-67E202887FBA) on build completion
default	12:05:18.190913 -0800	The Constructor	<Builder> did send data with tag 433
default	12:05:18.191139 -0800	The Constructor	<Builder> did send data with tag 0
default	12:05:18.263640 -0800	The Constructor	<Builder> did disconnect from socket

default	12:05:06.159392 -0800	Dringend	[Crashlytics] Version 3.4.1 (92)
default	12:05:06.495360 -0800	Dringend	Faulting in NSHTTPCookieStorage singleton
default	12:05:06.495577 -0800	Dringend	Faulting in CFHTTPCookieStorage singleton
default	12:05:06.495791 -0800	Dringend	Creating default cookie storage with default identifier
default	12:05:06.549263 -0800	Dringend	TIC TCP Conn Start [2:0x17018cf30]
default	12:05:06.661561 -0800	Dringend	TIC TCP Conn Start [1:0x17418c980]
default	12:05:08.120670 -0800	Dringend	TIC TCP Conn Event [1:0x17418c980]: 1 Err(0)
default	12:05:08.120902 -0800	Dringend	TIC TCP Conn Connected [1:0x17418c980]: Err(0)
default	12:05:08.121128 -0800	Dringend	TIC Enabling TLS [1:0x17418c980]
default	12:05:08.158041 -0800	Dringend	TIC TCP Conn Event [2:0x17018cf30]: 1 Err(0)
default	12:05:08.158271 -0800	Dringend	TIC TCP Conn Connected [2:0x17018cf30]: Err(0)
default	12:05:08.158514 -0800	Dringend	TIC Enabling TLS [2:0x17018cf30]
default	12:05:08.384886 -0800	Dringend	<private> adding listener `<private>` for service: iMessage
default	12:05:08.385419 -0800	Dringend	<private> creating monitor for service: iMessage
default	12:05:08.386510 -0800	Dringend	<private> updating availability for FTCServiceTypeiMessage   => from FTCServiceAvailabilityUnavailable to FTCServiceAvailabilityAvailable
default	12:05:08.881577 -0800	Dringend	TIC TLS Event [1:0x17418c980]: 2, Pending(0)
default	12:05:08.882198 -0800	Dringend	TIC TLS Event [2:0x17018cf30]: 2, Pending(0)
default	12:05:08.882451 -0800	Dringend	TIC TLS Event [1:0x17418c980]: 11, Pending(0)
default	12:05:08.886447 -0800	Dringend	TIC TLS Event [1:0x17418c980]: 12, Pending(0)
default	12:05:08.887298 -0800	Dringend	TIC TLS Event [1:0x17418c980]: 14, Pending(0)
default	12:05:08.888781 -0800	Dringend	TIC TLS Event [2:0x17018cf30]: 11, Pending(0)
default	12:05:08.912944 -0800	Dringend	TIC TLS Event [2:0x17018cf30]: 12, Pending(0)
default	12:05:08.919591 -0800	Dringend	TIC TLS Event [2:0x17018cf30]: 14, Pending(0)
default	12:05:08.920083 -0800	Dringend	TIC TLS Trust Result [1:0x17418c980]: 0
default	12:05:09.000884 -0800	Dringend	TIC TLS Trust Result [2:0x17018cf30]: 0
default	12:05:09.010065 -0800	Dringend	TIC TLS Event [1:0x17418c980]: 20, Pending(0)
default	12:05:09.066552 -0800	Dringend	TIC TCP Conn Event [1:0x17418c980]: 8 Err(0)
default	12:05:09.066793 -0800	Dringend	TIC TLS Handshake Complete [1:0x17418c980]
default	12:05:09.067328 -0800	Dringend	TIC TLS Event [2:0x17018cf30]: 20, Pending(0)
default	12:05:09.069766 -0800	Dringend	TIC TCP Conn Event [2:0x17018cf30]: 8 Err(0)
default	12:05:09.069990 -0800	Dringend	TIC TLS Handshake Complete [2:0x17018cf30]
default	12:05:09.086581 -0800	Dringend	TIC TCP Conn Cancel [1:0x17418c980]
default	12:05:14.492621 -0800	Dringend	<Commander> Zip for project will be located at '/private/var/mobile/Containers/Data/Application/191F0DFB-8239-4333-8041-2FA272A36745/tmp/project.zip'
default	12:05:14.604621 -0800	Dringend	<Commander> sending header dictionary: {
    buildOptions =     {
        destination = "generic/platform=iOS";
        scheme = imagenhance;
    };
    buildType = 0;
    dataLength = 18103;
    exportOptions =     {
    };
}
default	12:05:14.617882 -0800	Dringend	<Commander> connected to host
default	12:05:14.618793 -0800	Dringend	<Commander> wrote data with tag 33
default	12:05:14.619245 -0800	Dringend	<Commander> wrote data with tag 0
default	12:05:14.619665 -0800	Dringend	<Commander> wrote data with tag 343
default	12:05:14.620079 -0800	Dringend	<Commander> wrote data with tag 0
default	12:05:14.621254 -0800	Dringend	Stream client bypassing proxies on TCP Conn [3:0x17418d5b0]
default	12:05:14.621569 -0800	Dringend	TCP Conn 0x17418d5b0 started
default	12:05:14.635418 -0800	Dringend	<Commander> Did received return data
default	12:05:14.635626 -0800	Dringend	<Commander> was notified that socket connection was accepted and data was received
default	12:05:14.722562 -0800	Dringend	<Commander> Did received return data
default	12:05:14.722810 -0800	Dringend	<Commander> did read return header from socket
default	12:05:14.724622 -0800	Dringend	<Commander> Received output but no export data
default	12:05:14.746732 -0800	Dringend	TCP Conn 0x17418d5b0 canceled
default	12:05:14.752346 -0800	Dringend	<Commander> did disconnect with error (null)
default	12:05:17.994009 -0800	Dringend	<Commander> Zip for project will be located at '/private/var/mobile/Containers/Data/Application/191F0DFB-8239-4333-8041-2FA272A36745/tmp/project.zip'
default	12:05:18.079056 -0800	Dringend	<Commander> sending header dictionary: {
    buildOptions =     {
        destination = "generic/platform=iOS";
        scheme = imagenhance;
    };
    buildType = 1;
    dataLength = 18103;
    exportOptions =     {
        exportFormat = IPA;
    };
}
default	12:05:18.087396 -0800	Dringend	<Commander> connected to host
default	12:05:18.087707 -0800	Dringend	<Commander> wrote data with tag 33
default	12:05:18.087914 -0800	Dringend	<Commander> wrote data with tag 0
default	12:05:18.088850 -0800	Dringend	<Commander> wrote data with tag 343
default	12:05:18.089428 -0800	Dringend	<Commander> wrote data with tag 0
default	12:05:18.091116 -0800	Dringend	Stream client bypassing proxies on TCP Conn [4:0x17418d750]
default	12:05:18.091392 -0800	Dringend	TCP Conn 0x17418d750 started
default	12:05:18.150109 -0800	Dringend	<Commander> Did received return data
default	12:05:18.150245 -0800	Dringend	<Commander> was notified that socket connection was accepted and data was received
default	12:05:18.263679 -0800	Dringend	<Commander> Did received return data
default	12:05:18.265239 -0800	Dringend	<Commander> did read return header from socket
default	12:05:18.265743 -0800	Dringend	<Commander> Received output but no export data
default	12:05:18.286541 -0800	Dringend	TCP Conn 0x17418d750 canceled
default	12:05:18.303155 -0800	Dringend	<Commander> did disconnect with error (null)

**Comment by SquaredTiki** [comment]
Hey Farid,

Please could you upload a picture of your configuration in The Constructor? This is likely a code signing issue.

Thanks,
Josh

**Comment by faridk** [comment]
![app](https://user-images.githubusercontent.com/8215470/35259243-8bf0809c-ffb9-11e7-9fb6-01adfdef4fb1.png)

**Comment by SquaredTiki** [comment]
Thanks! Is your project using automatic or manual code signing? If automatic then you'll want to leave the `Code Signing Identity` field blank in The Constructor and set the provisioning profile to `Use project defaults`.

**Comment by faridk** [comment]
![app](https://user-images.githubusercontent.com/8215470/35311666-8874bd3a-006c-11e8-8867-a04c67479952.png)
Same error

**Comment by SquaredTiki** [comment]
Thanks for giving that a go. Can I confirm if you have a paid iOS developer program account? If not then unfortunately it's not currently possible to run projects as the method that Xcode uses to sign such builds is internal and not available for Dringend/The Constructor to use.

**Comment by faridk** [comment]
I don't have a paid iOS developer program account.
Thank you for your help!
