### ISSUE TITLE
Constructor port forwarding issue

### ISSUE THREAD

**Issue by RimeOCRLIB** [SquaredTiki/Dringend-Issues#123]
Good day.

After purchasing Dringend program in Apple Store we need connect it with Constructor program on MacOc ElCapitan through Xiaomi 3D router.

For now we can no any success in that even without firewall on MacOS.
Constructor remain in state «Port forwarding in progress» with no any message on any port value.
All another port forwarding services we have on router working well. Constructor can not use the TCP ports we have tested already for another services.
telnet also refuse connection to this Constructor service
telnet www.buddism.ru 6390
Trying 87.236.26.40...
telnet: connect to address 87.236.26.40: Connection refused
telnet: Unable to connect to remote host
It is no connection from iPad also - Connection refused report.

Any advice and help is really appreciated - program need for buddhism library project.

Alexander
www.buddism.ru

**Comment by SquaredTiki** [comment]
Hey Alexander! I'm sorry you've been having some issues with The Constructor but I'd gladly help get things working with you.

One thing to check if The Constructor remains in the 'Port forwarding in progress' state is that you have provisioning profiles installed on the Mac you're running The Constructor on. There is a bug that causes port forwarding to stall if The Constructor cannot locate any provisioning profiles.

Let me know if that helps and if not we can continue to debug the issue.

**Comment by RimeOCRLIB** [comment]
Great. Thank you for your help.
After create a free provisioning profile for iOS development in xCode we was able to build with Constructor after choose this profile.
