### ISSUE TITLE
Folders Syncing

### ISSUE THREAD

**Issue by isklikas** [SquaredTiki/Dringend-Issues#13]
So some of the folders synced properly when I replaced the files on Dropbox from my Mac, while some of the others remained the same. Could it have to do with syncing of folders, as the folders didn't sync?

**Comment by SquaredTiki** [comment]
Is the issue here that some of the files synced whilst others didn't? Which way round was the syncing, did it not sync from the app to your mac, or from your mac to the app? Thank you!

**Comment by isklikas** [comment]
It was from the Mac to the app and that happened to only some folders. To be precise, the content of the folder that did not sync, were folders .lproj. What showed up instead was a single Localizable.strings file which doesn't make sense.

**Comment by SquaredTiki** [comment]
It may be that Dringend was not displaying the other localizations under the single Localizable.strings file, see #20

**Comment by isklikas** [comment]
Yeah exactly, that seems to be the issue, because Base.lproj that showed up is my first localisation. So I guess you can close this, since the bug is dew scribes on issue 20.

**Comment by SquaredTiki** [comment]
Will do, thanks for bringing this to my attention though.

**Comment by isklikas** [comment]
No problem, it was just my way to get you on the right path :)
