### ISSUE TITLE
Plus button remains active

### ISSUE THREAD

**Issue by isklikas** [SquaredTiki/Dringend-Issues#18]
So, I clicked compile, then went back,then clicked plus, then got the alert and clicked plus again. This makes 2 plus dialogs appear on top of each other. I would also think that it makes sense to close it if it's open by tapping a different top button or the plus button again. Here is a video that explains the situation 

https://www.dropbox.com/s/jp1seq63k8zdtkz/Video%202-2-14%20-%203%2022%2042%20%CF%80.%CE%BC..mov

**Comment by SquaredTiki** [comment]
What's 'the alert' in the context of your description for reproducing the bug? Thanks.

**Comment by isklikas** [comment]
The alert is compile failed because my Mac was shut down.
