### ISSUE TITLE
Full support for localized .strings files

### ISSUE THREAD

**Issue by SquaredTiki** [SquaredTiki/Dringend-Issues#20]
Currently .strings files only open the first localization and do not allow you to choose a specific localization as Xcode does below:

![screen shot 2014-02-02 at 10 09 37](https://f.cloud.github.com/assets/146159/2060013/4edf465a-8bf2-11e3-8591-2dc9eb140336.png)

**Comment by isklikas** [comment]
Have in mind that despite Xcode shows them as a single file, in reality, in the file structure, there are 2 folders. So, folder 1: En.lproj > Localizable.strings. And folder 2. De.lproj > Localizable.strings. There simply isn't a single file available with the name Localizable.strings as Xcode says.
