### ISSUE TITLE
Workspace & cocoapods support

### ISSUE THREAD

**Issue by Noobish1** [SquaredTiki/Dringend-Issues#28]
Ability to setup and add cocoapods via the iPad app would be great.

**Comment by achappell** [comment]
This would definitely help my team!

**Comment by cannyboy** [comment]
This would be my number one request

**Comment by Tintenklecks** [comment]
YES YES YES … especially because nowadays everybody works with cocoa pods … and that needs workspaces

PLEEEEEEEEEASE!!!

**Comment by jayhickey** [comment]
Putting another vote into the hat. This would be my number one request as well.

**Comment by SquaredTiki** [comment]
Would you want to be able to add pods as you would via Terminal using the `pod install` command on a Mac?

**Comment by Tintenklecks** [comment]
It would be great of course! But the main thing is the support for workspaces. So if I could edit a POD-prepared project it would already be an invaluable addition
The ability to run the "pod install" after editing the pod file file would be the "freestyle" ;-)

**Comment by Tintenklecks** [comment]
Great job btw!!!

**Comment by jayhickey** [comment]
I agree with @Tintenklecks. Workspace support is the most important. Being able to install new pods in the app would be nice. However, for the time being I think many would be content if pods still had to be installed on the mac side, but workspace development containing said pods could be done in the app.

**Comment by jbowden1982** [comment]
I saw that you are planning workspace support.  I love the app and know you are jus getting going but ASIs I can only work on my personal projects because I can't build with workspace for my professional work.  Do you have a projected mvp release date for workspaces?  Oh and thanks for all the hard work once we have workspaces I will spend more time in this app then I do in any other.  Thanks😉

**Comment by SquaredTiki** [comment]
@jbowden1982 Pretty busy with things at the moment unfortunately but an ETA on this would be December time. Syncing (& cocoa-pods) is the key thing that is left. Thanks very much for the kind words!

**Comment by jbowden1982** [comment]
@SquaredTiki thanks man can't wait.  Appreciate such a quick response.

**Comment by ghost** [comment]
Is building a Cocoapods xcworkspace file supported as of now? I tried doing it with one of my projects in the latest version and it had issues with building the Pods.

**Comment by SquaredTiki** [comment]
@antgly Yes, however there can be some config issues if the project is imported through Dropbox (git repos are more reliable). What issues are you experiencing?

**Comment by ghost** [comment]
I'm assuming that it's because I didn't have the Pods committed now that I think of it. If you could add cocoapods installation somehow it's be awesome.

**Comment by SquaredTiki** [comment]
@antgly That would indeed be an issue, the Pods would need to be committed for it to build successfully.  Pods installation would be tricky but I'll note it as an enhancement request, thanks for the suggestion as I think it'd certainly be useful for others too.

**Comment by bitomule** [comment]
Is this currently expected to work? Purchased today but can't build project due to provisioning profile errors. (cocoapods has it's own bundle identifiers)

**Comment by SquaredTiki** [comment]
@bitomule Currently The Constructor applies one provisioning profile to the whole project so that may be why are seeing this error. Please could you try using [this beta version](http://dringend.cc/dl/constructor_1.1.1.zip) of The Constructor and select "Use project defaults" to see if that works for you?

**Comment by bitomule** [comment]
@SquaredTiki yes, that seems to have fixed it :) Now I only have one issue related to private key (I think certificate expired but that's not related to Drigend)

**Comment by SquaredTiki** [comment]
@bitomule Glad to hear it, I'll be releasing it as an update to everyone soon.
