### ISSUE TITLE
Possibility to use "The Constructor" without port forwarding

### ISSUE THREAD

**Issue by idoodler** [SquaredTiki/Dringend-Issues#30]
Hi, my router is not able to have port forwarding, so I can use "The Constructor". It would be awesome if you could add an option that allows us to build the app in our local network.

**Comment by SquaredTiki** [comment]
This should have been made more clear in the app really, apologies. You can still build your app on the local network using The Constructor.app but you will have to change the IP address used in Dringend from your public IP (the one you got from Google) to your private IP on your local network which you can find under Network in System Preferences.
