### ISSUE TITLE
iPhone app for compiling

### ISSUE THREAD

**Issue by ranjha** [SquaredTiki/Dringend-Issues#31]
It would be most helpful if there was an app for the iPhone that allowed us to compile the app on the iPhone, especially because most of my apps are made for the iPhone.

**Comment by Colton** [comment]
Do you realise how difficult a port is?

**Comment by MaxHasADHD** [comment]
You can run iPhone apps on iPad. my suggestion was to have the iPhone just as a server, so when you build it on the iPad, it will send the link to the IPhone to install. i think that will be best rather than a full editor which will be painful to port, and hard to edit. not much use for iPhone

**Comment by adamstener** [comment]
I think the idea to run the build on the phone would be great too!  The whole app doesn't need to be ported, just send the finished build to the selected device.

**Comment by ezhes** [comment]
+1 for the idea as using the iPhone as just a target. All it would take is just a system polling the dropbox folder or wherever the IPAs land for installing at just pull it. If @SquaredTiki could outline where the files are stored when building we could just build an app for it on the iPads

**Comment by SquaredTiki** [comment]
The early plan now, as of the release of the iPhone 6 and 6 Plus, is for a full version of the app for iPhone. What are the opinions on this?

@shusain93 The IPAs themselves are not stored on Dropbox, rather just the distribution manifest files are.

**Comment by MaxHasADHD** [comment]
I think that would be awesome! Can quickly update an app from anywhere, I like this plan!

**Comment by ezhes** [comment]
You closed the ticket, but I'm not sure what you meant? Does that mean you've added the feature or its a no go?

**Comment by SquaredTiki** [comment]
@shusain93 The latest version 1.4 adds iPhone support

**Comment by ezhes** [comment]
Oh awesome! Is it up in the review line already? I'd be excited to show this off to other people WWDC

**Comment by SquaredTiki** [comment]
@shusain93 It's out now in fact! See: https://twitter.com/dringendapp/status/606974304790659072
