### ISSUE TITLE
[BUG] Import error

### ISSUE THREAD

**Issue by athros** [SquaredTiki/Dringend-Issues#34]
https://www.dropbox.com/s/zoa4dz41m0ce2u0/dringend_import_error.png

Everytime I try to import a project, I get the above error for different files. I tried it 3 times, and it showed different files everytime. 

What would you like from me in order to help diagnose the problem?

**Comment by SquaredTiki** [comment]
-1001 is the code for an unknown error. In the upcoming update this is fixed by automatically attempting a re-download of files with this error. Until then if you sync the project after import it should download these missing files. Apologies for the inconvenience.

**Comment by athros** [comment]
No worries. Thank you for the response!
