### ISSUE TITLE
Support for .lua editing.

### ISSUE THREAD

**Issue by briarfox** [SquaredTiki/Dringend-Issues#35]
Would be nice if .lua files were supported with basic editing.

**Comment by SquaredTiki** [comment]
As plain text files or with syntax highlighting?

**Comment by briarfox** [comment]
Syntax highlighting would be great but basic text editing would be sufficient.

**Comment by SquaredTiki** [comment]
I've added support for viewing .lua files currently without syntax highlighting and this will be available in v1.1

**Comment by briarfox** [comment]
Great! Thank you.
