### ISSUE TITLE
Bracket detection

### ISSUE THREAD

**Issue by MaxHasADHD** [SquaredTiki/Dringend-Issues#38]
Detect the last bracket typed and if its open, return the closed version of that bracket. and detect if the place where the caret is currently at, then insert that type of bracket (round, curly or square)

**Comment by SquaredTiki** [comment]
Just wondering if you could clarify what you mean by 'detect if the place where the caret is currently at, then insert that type of bracket'. Thanks.

**Comment by MaxHasADHD** [comment]
So if you type [, clicking the button would insert ] automatically, or it it's ( it would put ) if clicked again but thinking now you can just insert (), [] or {} and move he carrot in the center
