### ISSUE TITLE
Crash when going back with the find and replace.

### ISSUE THREAD

**Issue by isklikas** [SquaredTiki/Dringend-Issues#4]
So there is a crash, usually the second time I tap back repeatedly or something like this.

**Comment by SquaredTiki** [comment]
I'm not able to reproduce this unfortunately, could you provide a series of steps to reliably reproduce this crash if possible? Thanks.

**Comment by isklikas** [comment]
I will attach a video file at the end that shows how to recreate the bug. It always happens randomly, so it can happen in the second, third, or fourth attempt. But, it always happens when tapping continuously. I found it out, when repeatedly tapping for a very common string. It might be the app running out of memory and thus disposing useful resources. 

Here is the video: https://www.dropbox.com/s/fkst6wh5wfe0sbd/Video%2028-1-14%20-%205%2050%2043%20%CE%BC.%CE%BC..mov

**Comment by SquaredTiki** [comment]
Thanks. I suspect it may well relate to the size of the file, how many lines does the file that crashed occurred in contain?

**Comment by isklikas** [comment]
It has 554 lines
