### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by mbcoder17** [SquaredTiki/Dringend-Issues#43]
When I try to build an app I get this UIAlertView:

Initiating build failed
An error occurred whilst attempting to initiate the build process with the build server, the error is as follows: Read-operation timed out

Any ideas?

**Comment by SquaredTiki** [comment]
This may relate to #39. Does restarting The Constructor make any difference?

**Comment by mbcoder17** [comment]
Nope, still getting the same error :(

**Comment by SquaredTiki** [comment]
Are you building a template project or your own project? If your own does it normally take longer than 30 seconds to build on your Mac?

**Comment by mbcoder17** [comment]
I just created a new template project within the app and built it

**Comment by SquaredTiki** [comment]
Can you check that on your Mac in System Preferences > Security & Privacy > Firewall > Firewall Options that The Constructor has the option 'Allow incoming connections' beside it.

**Comment by mbcoder17** [comment]
Yes, that option is checked

**Comment by SquaredTiki** [comment]
Interesting. What is the model of the Mac that is acting as the build server?

**Comment by mbcoder17** [comment]
I believe it is a 2009 MacBook Pro. Do you need more specific info?

**Comment by SquaredTiki** [comment]
I believe this may be the same problem as described in #39. That being that if the project takes longer than 30 seconds to build on the build server the connection times out. One way to test this is to export the template project and build it on your Mac and see how long it takes to build. Either way the issue described will be fixed in the next update. I apologize for the current issues.

**Comment by mbcoder17** [comment]
I will try that and let you know what happens. Thank you for the quick replies, I look forward to the next update!

**Comment by SquaredTiki** [comment]
Thanks!

**Comment by mbcoder17** [comment]
So I just built it on my Mac and it took way longer than 30 seconds, hopefully it is the issue you are referring to. When do you think the next update will be out?

**Comment by SquaredTiki** [comment]
If that's the case then it most likely is so I will close this one as a duplicate for now. This issue (#39) is the last thing to fix for the update, then there'll be a brief beta testing period followed by submittal to the App Store which all going well should be next week.
