### ISSUE TITLE
Never-ending sync

### ISSUE THREAD

**Issue by mbcoder17** [SquaredTiki/Dringend-Issues#45]
I'm having an issue when I sync my files with Dropbox. I made a change to one of them on my Mac, and when I press the little refresh button on the app, it just says syncing at the top until I quit the app, but the files don't update.

Any ideas?

**Comment by SquaredTiki** [comment]
If you could check your devices log whilst the never-ending sync is happening and report back with the contents of it during the sync that would be greatly helpful. Thanks,

**Comment by mbcoder17** [comment]
Been busy lately, I will try to get you the log info tomorrow...

**Comment by mbcoder17** [comment]
Sorry about the wait...here ya go:

Mar 23 10:50:05 Jacobs-iPad kernel[0] <Debug>: launchd[814] Container: /private/var/mobile/Applications/30C6968A-156E-4436-BF7F-07BBB70C772A (sandbox)
Mar 23 10:50:05 Jacobs-iPad backboardd[31] <Error>: HID: The 'Passive' connection 'Dringend' access to protected services is denied.
Mar 23 10:50:19 Jacobs-iPad Dringend[814] <Warning>: Metadata for file (DRDetailViewController.m) loaded
Mar 23 10:50:19 Jacobs-iPad Dringend[814] <Warning>: Metadata for file (InfoPlist.strings) loaded
Mar 23 10:50:19 Jacobs-iPad Dringend[814] <Warning>: Metadata for file (DRAppDelegate.m) loaded
Mar 23 10:50:19 Jacobs-iPad Dringend[814] <Warning>: Metadata for file (DringTest-Info.plist) loaded
Mar 23 10:50:19 Jacobs-iPad Dringend[814] <Warning>: Metadata for file (DringTest-Prefix.pch) loaded
Mar 23 10:50:19 Jacobs-iPad Dringend[814] <Warning>: Metadata for file (DRAppDelegate.h) loaded
Mar 23 10:50:19 Jacobs-iPad Dringend[814] <Warning>: Metadata for file (DRMasterViewController.m) loaded
Mar 23 10:50:19 Jacobs-iPad Dringend[814] <Warning>: Metadata for file (main.m) loaded
Mar 23 10:50:19 Jacobs-iPad Dringend[814] <Warning>: Metadata for file (DRDetailViewController.h) loaded
Mar 23 10:50:19 Jacobs-iPad Dringend[814] <Warning>: Metadata for file (Images.xcassets) loaded
Mar 23 10:50:19 Jacobs-iPad Dringend[814] <Warning>: Metadata for file (Main.storyboard) loaded
Mar 23 10:50:19 Jacobs-iPad Dringend[814] <Warning>: Metadata for file (DRMasterViewController.h) loaded
Mar 23 10:50:20 Jacobs-iPad Dringend[814] <Warning>: [ERROR] DBRequest#connectionDidFinishLoading: error moving temp file to desired location: The operation couldn’t be completed. (Cocoa error 4.)
Mar 23 10:50:20 Jacobs-iPad Dringend[814] <Warning>: [WARNING] DropboxSDK: error making request to /1/files/dropbox/DringTest/DringTest.xcodeproj/project.pbxproj - (4) Error Domain=NSCocoaErrorDomain Code=4 "The operation couldn’t be completed. (Cocoa error 4.)" UserInfo=0x14de8780 {path=/DringTest/DringTest.xcodeproj/project.pbxproj, destinationPath=/private/var/mobile/Applications/30C6968A-156E-4436-BF7F-07BBB70C772A/tmp.xcodeproj/project.pbxproj}
Mar 23 10:50:20 Jacobs-iPad Dringend[814] <Warning>: Unable to download Xcode project PBX file due to error: Error Domain=NSCocoaErrorDomain Code=4 "The operation couldn’t be completed. (Cocoa error 4.)" UserInfo=0x14de8780 {path=/DringTest/DringTest.xcodeproj/project.pbxproj, destinationPath=/private/var/mobile/Applications/30C6968A-156E-4436-BF7F-07BBB70C772A/tmp.xcodeproj/project.pbxproj}

Should I try creating a new project or something?

**Comment by SquaredTiki** [comment]
Thanks for the logs, I've been able to figure out what this is now (assuming the project you were trying to sync had been exported). I've fixed it and the fix will be pushed out in the next update.

**Comment by mbcoder17** [comment]
Yes, I believe I exported it from Dringend to dropbox. Thanks!
