### ISSUE TITLE
Comments at the top of each file need to be updated

### ISSUE THREAD

**Issue by MaxHasADHD** [SquaredTiki/Dringend-Issues#52]
The comment with the file name, created by date and copyright needs to be updated. says "created by A 2Code user" and the copyright says __MyCompanyName_

**Comment by SquaredTiki** [comment]
Thanks for bringing this my attention, something I've been meaning to sort out for a while. Where in your opinion would be the best place for the user to enter their name and company name? In the new project dialog or perhaps in Settings?

**Comment by MaxHasADHD** [comment]
In each new app put it there, but make it also save and load automatically and when it's changed it's also changed in settings maybe? Or just in settings.

**Comment by SquaredTiki** [comment]
Thanks Max. Fixed in 1.1.1.
