### ISSUE TITLE
The Constructor app has no icon in dock or in OSX menu bar

### ISSUE THREAD

**Issue by funky-monkey** [SquaredTiki/Dringend-Issues#61]
Also CMD-Tab does not seem to work to bring the app forward.
Maybe add it as an setting? And that makes it pretty annoying to find the app when there are a lot of windows open.

I did however find the 'Check update' easter-egg by clicking on the logo :-)

**Comment by SquaredTiki** [comment]
Having the app with no dock icon or presence in the menu bar was meant originally to keep it low profile and in the background. Would your preference be for a setting to enable or disable the dock icon? I don't think a status item would particularly suit this kind of app.

Glad you noticed that one :) Though if I was to include this setting I'd likely add a separate settings window and migrate the check for updates option there.

**Comment by alessaba** [comment]
i'd like settings menu and the option to show the service in the status bar

**Comment by funky-monkey** [comment]
I'd like to have services run in the status bar, not the dock. With an option menu. But that is personal preference ;-)

**Comment by SquaredTiki** [comment]
Seems like a status bar item is popular suggestion, more so than the dock.

@funky-monkey What options would you like in the menu?

**Comment by jmurff** [comment]
Right now it isn't able to be set to start at login from within the App. That would be nice so you can set it and forget it.

**Comment by jayhickey** [comment]
Right now the only way I know of to kill the app if from the command line or with the activity monitor. This is not a good thing. I also agree with a status bar item.

I think it would be helpful for the menu to show the port number, and maybe have a link to the FAQ on your site

**Comment by Noobish1** [comment]
+1 for it being in the menu bar

**Comment by SquaredTiki** [comment]
@jayhickey You can quit the app by double clicking on the app icon in finder then pressing Command-Q or by putting the window into focussing and pressing Command-Q.

However, I do hear you all loud and clear about wishing for it to be in the menu bar. Would the status item just show The Constructor when clicked or would some options be wanted in there?

**Comment by alessaba** [comment]
i'd like the status icon and the quit setting

Filippo Claudi

**Comment by SquaredTiki** [comment]
@filippocld Do you mean a quit option in the menu presented from the status item?

**Comment by jayhickey** [comment]
@SquaredTiki I think it would be fine if it just showed The Constructor when clicked. It's kind of a "set it and forget it" app, so now that I think about it more I don't see a need for any menu options.

**Comment by alessaba** [comment]
Exactly

Filippo Claudi

**Comment by alessaba** [comment]
maybe
left click: open app
right click: exit app and other future settings

Filippo Claudi
