### ISSUE TITLE
Dropbox sync issues

### ISSUE THREAD

**Issue by jmurff** [SquaredTiki/Dringend-Issues#68]
1) I have noticed the dropbox popup doesn't seem to update after first time. I created a directory and it never showed up it the app until I completely quit the app.

2) I was editing a file and the app crashed. I restarted the app all work was gone. _sigh_ 
(see other feature request for autosave) but i knew what i did and while it was still fresh in my brain i thought i'll just sync project to dropbox and edit it on my mac quickly so i can have the code completion etc. So I did that. Ran it in simulator all happy and cool. went back to ipad and the files had not changed. hmmm. went back to my mac and files had changed back to what was on my ipad!!! lost all my work _AGAIN_! _sigh_.

**Comment by SquaredTiki** [comment]
I'm sorry to hear about your issues, especially with the case of losing some of your work. Seems like a very odd scenario for this to happen.

Firstly, what do you mean when you say that 'the dropbox popup doesn't seem to update after first time'? Is that the pop up when you are importing a project? The directory may take a little time to show up as Dropbox has to sync it, but dismissing the popover and bringing it back up again a couple of seconds later should show it.

As for point number 2, whilst you were making changes on your Mac what was Dringend on your iPad doing? Was your iPad on or sleeping? Was Dringend the active app? And also was the file you were editing on your Mac also open for editing in Dringend? Also when you went back to your Mac and you noticed the files had changed back was there not a conflicted copy of the file in the same folder?

**Comment by jmurff** [comment]
Its no problem i _LOVE_ this app and everything it is and it can become. I expect issues to crop up and it may just be L-user issues.
1) i never seemed to see the directory even waiting. ill try some more to be sure.

 2) My ipad was asleep and at the projects window i believe. i went into the project and pulled up the file and it was old file. I just checked and you are correct the _is_ conflicted files in my dropbox dir (hurray! totally forgot about that possibility!). Those are not showing up in my project on the app though. Are you filtering? oh i see any files not into the xcode project as of yet never show up. ok maybe this is me being a dope. i'll try some more things. sorry for possible red herring.

**Comment by SquaredTiki** [comment]
Thanks very much!

1) Okay, thank you. I will do some testing for this to be sure as well.

2) I think I can see how this occurred: If you pulled up the file in Dringend and then went back (before syncing) then that would have meant that the file was then saved again and thus its modification date updated to that time. When you then synced it was found that the modification date of the file on the iPad was newer than that of the copy on your Mac and thus the copy on your iPad was seen as the most up to date one. However as the one on your Mac had also been modified then a conflicted copy was created just in case Dringend was wrong (safety first). 

You are right that they will not show up as Dringend will only display files that are file references within Xcode.
