### ISSUE TITLE
Automatic saving of files?

### ISSUE THREAD

**Issue by jmurff** [SquaredTiki/Dringend-Issues#69]
Any way an autosave feature could be added so as to minimize loss on a crash. A setting perhaps? It might cause dropbox sync issues if you leave ipad app running and edit on the mac (see dropbox syncing issues) but as long as it is noted to completely quit the app before editing on mac perhaps that is enough?

**Comment by SquaredTiki** [comment]
This is a good suggestion and a setting for this I'd agree would be a good idea. What kind of interval would you want for autosaving?

Sync issues might be problematic, I'll have a think on that.

**Comment by jmurff** [comment]
Most editors have it as a setting in seconds. i'd not let it be set to low though as that would cause you issues i'd imagine. probably no lower than 30 secs?

**Comment by SquaredTiki** [comment]
Yep minimum of 30 seconds would make sense.

**Comment by alessaba** [comment]
I'd love this request in version 1.2 sometimes i lost lines of hard work 😔
i'd set 30/40 secs

**Comment by SquaredTiki** [comment]
@filippocld I'm sorry to hear that. Might I ask what caused you to lose some of your work? Was it a syncing issue? If so it's worth checking the same folder that the file you lost work is in for a conflicted copy.

**Comment by alessaba** [comment]
i have used my app for a while and Dringend has finished the background time,and ios has closed it .Dringend hasn't synced before the running of the app and then work lost
i'd love autosaving and also autosync

**Comment by SquaredTiki** [comment]
@filippocld I think I understand the situation in which changes were lost. Thank you.
