### ISSUE TITLE
.strings files

### ISSUE THREAD

**Issue by isklikas** [SquaredTiki/Dringend-Issues#7]
All of my projects have localizations, so I receive many of them on the go. It would be very handy to be able to edit these files on the go, so that the translations will be done without opening Xcode.

**Comment by SquaredTiki** [comment]
Are the separate .strings files visible and it's just not possible to edit them?

**Comment by isklikas** [comment]
No, they appear greyed out. It says that Dringend does not support this filetype

**Comment by SquaredTiki** [comment]
Thanks, this is fixed in the next beta.
