### ISSUE TITLE
Commenting out lines and uncommenting

### ISSUE THREAD

**Issue by MaxHasADHD** [SquaredTiki/Dringend-Issues#72]
I think holding the // button should add // to the very beginning of the line but if is already there then uncomment it out. That would be awesome to easily comment lines to test stuff

**Comment by alessaba** [comment]
i agree. it would be cool

Filippo Claudi

**Comment by SquaredTiki** [comment]
Saw this when you first posted and it's a great idea — wanted to follow up on it now. At the moment holding the <kbd>//</kbd> key gives the user the option to insert a `/*` or a `*/`. How would you propose to maintain this functionality as well as including the functionality you'd like with (un)commenting the whole line?
