### ISSUE TITLE
Swift support

### ISSUE THREAD

**Issue by SquaredTiki** [SquaredTiki/Dringend-Issues#78]
- Swift syntax highlighting
- Swift project templates
- Swift file templates

**Comment by SquaredTiki** [comment]
Implemented in v1.2.2.

**Comment by funky-monkey** [comment]
Why don't you also put this on your product page at http://dringend.cc/ that your app supports Swift?

**Comment by SquaredTiki** [comment]
@funky-monkey Thanks for the suggestion, I've updated it in a couple of places to make it clearer.
