### ISSUE TITLE
.bundle files

### ISSUE THREAD

**Issue by isklikas** [SquaredTiki/Dringend-Issues#8]
.bundle files are used for localizations in bundles, so that the localisations are well ordered in the bundle. .bundle files are not actually files, they are folders with an extension on the end. Like the .app that are folders, which are opened on a Mac by right click, Show Package Contents. Even xcode shows these bundles as folders.

**Comment by SquaredTiki** [comment]
Further support required, deleting files and importing/exporting files from .bundle files and folder references not yet completed. Work on this continues.
