### ISSUE TITLE
Constructor App doesn't show up in the dock

### ISSUE THREAD

**Issue by roddi** [SquaredTiki/Dringend-Issues#83]
So there is no indication whether it is running, no way to start it up at login and no way to switch to its UI.

**Comment by SquaredTiki** [comment]
At the moment The Constructor runs entirely in the background. Presently if you wish to start it up at login you can add it as a login item in System Preferences. To display its UI you can double click on the the app icon in Finder again. However the plan is to add some preferences to allow the user the option as to whether it appears in the dock or menu bar and also to set it as a login item. See that discussion here: #61
