### ISSUE TITLE
Can connect to local IP but not to remote IP

### ISSUE THREAD

**Issue by ncperry** [SquaredTiki/Dringend-Issues#84]
I have the constructor running. And it says port forwarding successful.

When I connect using the local address: 192.168.0.4:6000, it works just fine.

However when I use the non-local address: ###.###.78.17:6000, it tells me:

Initiating build failed. An error ocurred whilst attempting to initiate the build process with the build server, the error is as follows: Connection refused

I do have port forwarding turned on for port 6000:

![screen shot 2014-10-12 at 11 04 37 am](https://cloud.githubusercontent.com/assets/1417659/4606802/df9758e4-5231-11e4-88e6-877516ef80a3.png)

Any ideas?

**Comment by SquaredTiki** [comment]
Have you manually set up port forwarding as well as the constructor doing it automatically? It's only recommended to do one, e.g. if you The Constructor says it is successful then there's no need to do it manually too. If there are issues nonetheless then the first step would be check to see if the port is actually open using port forwarding tester like [this one](http://www.yougetsignal.com/tools/open-ports/).

**Comment by ncperry** [comment]
Ok I changed the port to 6001. The constructor still says Port Forwarding Successful. I used the tool you suggested and it tells me the port is open. This did change the error message I got to:

"Initiating build failed
An error ocurred whilst attempting to initiate the build process with the build server, the error is as follows: Attempt to connect to host timed out"

Both iPad and server were connected to the internet when I did the test, so I don't know why they couldn't find each other.

**Comment by SquaredTiki** [comment]
That's good, seems like the port is correctly open now but for whatever reason no response is returned. Have you got the firewall enabled on your Mac and if so is The Constructor an authorized application (should be if 'Automatically allow signed software to receive incoming connections' is checked).

Also, when you initiate the build does the number next to the eye in The Constructor increase or remain at 0?

**Comment by ncperry** [comment]
I just checked, and my firewall is all the way off.

I tried building and I did not see the number next to the eye increment.

**Comment by SquaredTiki** [comment]
Thanks for checking those. Are you able to confirm that there's no firewall on your router either which may be blocking incoming connections from the WAN?

Could you also execute both of the following commands in Terminal and post their output please:

```
ping <your IP>
telnet <your IP> 5461
```

When you are testing the remote IP are you doing so from the local network or from another network?

Apologies for the inconvenience.

**Comment by ncperry** [comment]
Sorry it took me a bit to get back to this. Wow I didn't even know routers had firewalls. I logged into my router and this is what it tells me about firewall status:
![screen shot 2014-10-19 at 12 29 12 am](https://cloud.githubusercontent.com/assets/1417659/4692295/e7606d2c-5759-11e4-9731-4af19066b50b.png)

I went over to firewall settings, and I I clicked disable firewall, so it looks like this:
![screen shot 2014-10-19 at 12 33 00 am](https://cloud.githubusercontent.com/assets/1417659/4692298/06e3bcda-575a-11e4-89ba-79a7c8313aaf.png)

Both your ping text and the telnet test timed out:

Retina:~ ncperry$ ping ###.##.###.##
PING ###.##.###.## (###.##.###.##): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2

telnet ###.##.###.## 5461
Trying ###.##.###.##...
telnet: connect to address ###.##.###.##: Operation timed out
telnet: Unable to connect to remote host

I am testing from the local network. If not I would not have been able to do the 192.168.0.4:6000 test in the first post.

Thanks for the very prompt customer service. I appreciate it.

**Comment by SquaredTiki** [comment]
No worries and thank you for the detailed reply. It seems that your router isn't responding to ICMP requests (as can be seen when you `ping`) which may be indicative that it is still blocking other requests from the WAN too. May I ask what router you are using?

Could you also try running `traceroute <your IP>` and post the output please.

Thanks!

**Comment by ncperry** [comment]
Yeah it's a Zyxel C1000Z.

I did the traceroute thing, and I've let it go for 10 minutes or so. This is the output so far. Should I keep on waiting?

traceroute to  (), 64 hops max, 52 byte packets
 1  \* \* *
 2  \* \* *
 3  \* \* *
 4  \* \* *
 5  \* \* *
 6  \* \* *
 7  \* \* *
 8  \* \* *
 9  \* \* *
10  \* \* *
11  \* \* *
12  \* \* *
13  \* \* *
14  \* \* *
15  \* \* *
16  \* \* *
17  \* \* *
18  \* \* *
19  \* \* *
20  \* \* *
21  \* \* *
22  \* \* *
23  \* \* *
24  \* \* *
25  \* \* *
26  \* \* *

**Comment by SquaredTiki** [comment]
You can stop traceroute, apologies for not mentioning that. It appears that traceroute has failed as it should terminate eventually. Looking into your specific router model now, will get back to you as soon as possible.

**Comment by SquaredTiki** [comment]
From some [research](http://www.donationcoder.com/forum/index.php?topic=36001.0) it appears that your router does not support [NAT Loopback](http://en.wikipedia.org/wiki/Network_address_translation#NAT_loopback). Without NAT Loopback you won't be able to connect to your own public IP (e.g. `ping`, `traceroute`, use The Constructor etc.) from within your LAN. 

If you were to connect to your public IP from another network then all should work fine however it looks as if you will need to use your Mac's local IP (`192.168.0.4`) in Dringend as the build host IP when working from the LAN.

Apologies that this doesn't quite solve the issue and is more of a workaround but it appears to be the only solution given that the C1000Z doesn't support NAT Loopback.
