### ISSUE TITLE
In iOS 8 (Or possibly lower) when you use build and run the popup will always always show

### ISSUE THREAD

**Issue by ezhes** [SquaredTiki/Dringend-Issues#85]
So the issue is that when you choose the option for the warning to never be shown again it doesn't actually save. The pop up shows up **_every single time**_ which causes a royal pain when trying to debug an app. 

Is there a key I can add to `NSUserDefaults` to kill it? Or is this an issue in the app?

**Comment by SquaredTiki** [comment]
This was unfortunately an error in the code (due to an ill-formatted preprocessor macro) which resulted in the pop up showing regardless of the user defaults value. This has been fixed in the next update and I do apologize for the pain it is at present.
