### ISSUE TITLE
Clone git repo with SSH Key authentication

### ISSUE THREAD

**Issue by mlumbroso** [SquaredTiki/Dringend-Issues#90]
Hello,

my git server only allows access with a SSH key, is there any way I can manage to clone the repository and do the usual push and pull?

Thanks

**Comment by SquaredTiki** [comment]
Unfortunately it's not possible to clone using public/private keys with SSH at present but I shall mark this as an enhancement request for the future.

**Comment by mlumbroso** [comment]
Thanks for your reply.

Do you have an idea on the availability? Or a workaround?
I have no use of the app if I can't use my protected repo.

**Comment by SquaredTiki** [comment]
I've had a similar request previously so this is something I'll look into having done for the next update.

In the meantime: You could set up your git server to allow access via HTTPS (by way of a username and password, like GitHub) or perhaps mirror your repository on GitHub, see: https://help.github.com/articles/about-github-mirrors/.

**Comment by mlumbroso** [comment]
Hello,

any update on when it will be done?

Thanks for your time!

**Comment by SquaredTiki** [comment]
The new update is going to include iPhone support which is a fairly large task so I can't put a date on it at present. Apologies.
