### ISSUE TITLE
Clone branch from Git

### ISSUE THREAD

**Issue by ezhes** [SquaredTiki/Dringend-Issues#97]
I'm not sure if this feature has already been implemented into the app, but I need to clone a specific branch into the app. My current workflow has a release branch (origin/master) and a developement branch (origin/dev) and Dringend will automaticly checkout the master without giving an option to switch branchs.

**Comment by SquaredTiki** [comment]
If you clone the repo as normal then once you have cloned the repo there is an option to switch branch in the git menu.

**Comment by ezhes** [comment]
D'oh. Thanks. Should have exploed the app further. Thank you.
